# Generated by Django 3.2 on 2021-04-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='images')),
                ('price1', models.PositiveIntegerField(null=True)),
                ('price2', models.PositiveIntegerField()),
                ('price3', models.PositiveIntegerField()),
                ('dicr', models.TextField(null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.items')),
            ],
        ),
    ]
