# Generated by Django 3.2 on 2021-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='images')),
                ('name', models.CharField(max_length=200, null=True)),
                ('decr', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='types',
            name='price1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='types',
            name='price2',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='types',
            name='price3',
            field=models.FloatField(null=True),
        ),
    ]
