# Generated by Django 3.2 on 2021-06-02 09:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Array',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ConForm_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.PositiveIntegerField()),
                ('addr', models.TextField()),
                ('link', models.FileField(upload_to='', verbose_name=hotel.models.Types)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Order not packed', 'Order not packed'), ('Ready to Dlivery', 'Ready to Dlivery'), ('Order Deliveried', 'Order Deliveried')], default='Order not packed', max_length=150)),
                ('delivery_boy_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
