# Generated by Django 3.2 on 2021-06-02 09:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_array_conform_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), size=None),
        ),
    ]
