# Generated by Django 3.2 on 2021-06-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_array_array'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Array',
        ),
        migrations.RemoveField(
            model_name='conform_orders',
            name='link',
        ),
    ]
