# Generated by Django 3.2 on 2021-06-05 04:58

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210603_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='conform_orders',
            name='json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
