# Generated by Django 3.2 on 2021-06-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20210605_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types',
            old_name='price1',
            new_name='price',
        ),
    ]
