# Generated by Django 3.2 on 2021-06-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20210612_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conform_orders',
            name='advance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
