# Generated by Django 3.2 on 2021-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_conform_orders_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='conform_orders',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
