# Generated by Django 3.2 on 2021-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_conform_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conform_orders',
            name='advance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
