# Generated by Django 3.2 on 2021-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_rename_total_conform_orders_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conform_orders',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
